config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :films do
    member do
      post :favorite
      post :dislikes
    end
    resources :comments
  end

  namespace :account do
    resources :films
    resources :comments
  end
  
  root "films#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :film
  belongs_to :user

  validates :content, presence: true
  scope :recent, -> { order("created_at DESC") }
end

app/models/film.rb
class Film < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :film_relationships
  has_many :followers, through: :film_relationships, source: :user
end

app/models/film_relationship.rb
class FilmRelationship < ApplicationRecord
  belongs_to :film
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :films
  has_many :comments
  has_many :film_relationships
  has_many :favorited_films, through: :film_relationships, source: :film

  def is_follower_of?(film)
    favorited_films.include?(film)
  end

  def favorite!(film)
    favorited_films << film
  end

  def dislikes!(film)
    favorited_films.delete(film)
  end
end

app/controllers/account/comments_controller.rb
class Account::CommentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @comments = current_user.comments
  end
end

app/controllers/account/films_controller.rb
class Account::FilmsController < ApplicationController
  before_action :authenticate_user!

  def index
    @films = current_user.favorited_films
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_comment_and_check_permission, only: [:edit, :update, :destroy]
  before_action :find_film_and_check_permission, only: [:new, :create]

  def new
    @comment = Comment.new
  end

  def edit
    @film = @comment.film
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.film = @film
    @comment.user = current_user
    if @comment.save
      current_user.favorite!(@film)
      redirect_to film_path(@film)
    else
      render :new
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to account_comments_path, notice: "Update Success"
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to account_comments_path, alert: "Comment deleted"
  end

  private

  def find_comment_and_check_permission
    @comment = Comment.find(params[:id])
    if current_user != @comment.user
      redirect_to root_path, alert: "You have no permission."
    end
  end

  def find_film_and_check_permission
    @film = Film.find(params[:film_id])
    if !current_user.is_follower_of?(@film)
      redirect_to root_path, alert: "You have no permission."
    end
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_film_and_check_permission, only: [:edit, :update, :destroy]

  def index
    @films = Film.all
  end

  def show
    @film = Film.find(params[:id])
    @comments = @film.comments.recent.paginate( page: params[:page], per_page: 5)
  end

  def new
    @film = Film.new
  end

  def edit
  end

  def create
    @film = Film.new(film_params)
    @film.user = current_user

    if @film.save
      redirect_to films_path
    else
      render :new
    end
  end

  def update
    if @film.update(film_params)
      redirect_to films_path, notice: "Update Success"
    else
      render :edit
    end
  end

  def destroy
    @film.destroy
    redirect_to films_path, alert: "Movie deleted"
  end

  def favorite
    @film = Film.find(params[:id])
    if !current_user.is_follower_of?(@film)
      current_user.favorite!(@film)
      flash[:notice] = "收藏电影成功！"
    else
      flash[:warning] = "你已经收藏过这部电影！"
    end
    redirect_to film_path(@film)
  end

  def dislikes
    @film = Film.find(params[:id])
    if current_user.is_follower_of?(@film)
      current_user.dislikes!(@film)
      flash[:alert] = "已取消收藏电影！"
    else
      flash[:warning] = "你没有收藏这部电影，怎么取消 XD"
    end
    redirect_to film_path(@film)
  end

  private

  def find_film_and_check_permission
    @film = Film.find(params[:id])
    if current_user != @film.user
      redirect_to root_path, alert: "You have no permission."
    end
  end

  def film_params
    params.require(:film).permit(:title, :description)
  end
end

app/helpers/account/comments_helper.rb
module Account::CommentsHelper
end

app/helpers/account/films_helper.rb
module Account::FilmsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning" }.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/views/comments/_form.html.erb
<%= simple_form_for [@film, @comment] do |f| %>
  <div class="form-group">
    <%= f.input :content, input_html: { class: "form-control" } %>
  </div>
  <div class="form-action">
    <%= f.submit "Submit", data: { disable_with: "Submiting..." }, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>编辑评论</h2>
  <%= render "form" %>
</div>

app/views/comments/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>新增评论</h2>
  <%= render "form" %>
</div>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">x</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©️ 2017 Moives
    <br>Design by
    <a href="http://alexpan-blog.logdown.com/" target=_new>Alex</a>
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar navbar-header">
      <a class="navbar navbar-brand" href="/">Movies</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><%= link_to("注册", new_user_registration_path) %></li>
          <li><%= link_to("登录", new_user_session_path) %></li>
        <% else %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              Hi!, <%= current_user.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to("Favorited Films", account_films_path) %></li>
              <li><%= link_to("My Comments", account_comments_path) %></li>
              <li class="divider"></li>
              <li><%= link_to("退出", destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/films/_film_item.html.erb
<tr>
  <td>#</td>
  <td><%= link_to(film.title, film_path(film)) %></td>
  <td><%= film.description %></td>
  <td><%= film.user.email %></td>
  <td>
    <%= link_to("Edit", edit_film_path(film), class: "btn btn-default btn-sm") %>
    <%= link_to("Delete", film_path(film), class: "btn btn-default btn-sm",
                  method: :delete, data: { confirm: "Are you sure?"}) %>
  </td>
</tr>

app/views/films/_form.html.erb
<div class="form-group">
  <%= simple_form_for @film do |f| %>
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :description, input_html: { class: "form-control"} %>
    <%= f.submit "Submit", data: { disable_with: "Submiting..." }, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/films/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2 class="text-center">编辑电影</h2>
  <%= render "form" %>
</div>

app/views/films/index.html.erb
<div class="col-md-12">
  <%= link_to("New Movie", new_film_path, class: "btn btn-primary pull-right") %>
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Title</th>
        <th>Description</th>
        <th>Creator</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "film_item", collection: @films, as: :film %>
    </tbody>
  </table>
</div>

app/views/films/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2 class="text-center">新建电影</h2>
  <%= render "form" %>
</div>

app/views/films/show.html.erb
<div class="col-md-12">
  <div class="group">
    <% if current_user %>
      <% if current_user == @film.user %>
        <%= link_to("Edit", edit_film_path(@film), class: "btn btn-primary pull-right") %>
      <% end %>
      <span class="pull-right">
        <% if current_user.is_follower_of?(@film) %>
          <%= link_to("Write a Comment", new_film_comment_path(@film), class: "btn btn-default pull-right") %>
          <label class="label label-success"> 已收藏 </label>
          <%= link_to("Dislikes", dislikes_film_path(@film), class: "btn btn-default", method: :post) %>
        <% else %>
          <label class="label label-warning"> 未收藏 </label>
          <%= link_to("Favorite", favorite_film_path(@film), class: "btn btn-default", method: :post) %>
        <% end %>
      </span>
    <% end %>
  </div>

  <h2><%= @film.title %></h2>
  <p><%= @film.description %></p>

  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>评论内容</th>
        <th>发表者</th>
        <th>发表时间</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @comments.each do |comment| %>
        <tr>
          <td>#</td>
          <td><%= comment.content %></td>
          <td><%= comment.user.email %></td>
          <td><%= comment.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="text-center">
    <%= will_paginate @comments %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <%= yield %>
    </div>
    <%= render "common/footer" %>
  </body>
</html>